#!/usr/bin/env bash
# Rebuilds Terraform state after gs://naxos-503510 (the state backend) was lost.
# Resource ids come from the prior state embedded in terraform/plan.out (2026-08-11).
# Recreate the bucket and terraform init before running this from terraform/.
set -euo pipefail

terraform import 'google_artifact_registry_repository.images' 'projects/naxos-503510/locations/asia-northeast1/repositories/naxos'
terraform import 'google_bigquery_dataset.audit' 'projects/naxos-503510/datasets/naxos_audit'
terraform import 'google_bigquery_table.runs' 'projects/naxos-503510/datasets/naxos_audit/tables/runs'
terraform import 'google_bigquery_table.tool_calls' 'projects/naxos-503510/datasets/naxos_audit/tables/tool_calls'
terraform import 'google_cloud_run_v2_job.sandbox["default"]' 'projects/naxos-503510/locations/asia-northeast1/jobs/naxos-sbx-default'
terraform import 'google_cloud_run_v2_job_iam_member.sandbox_runner["default"]' 'projects/naxos-503510/locations/asia-northeast1/jobs/naxos-sbx-default/roles/run.invoker/serviceAccount:naxos2-api@naxos-503510.iam.gserviceaccount.com'
terraform import 'google_cloud_run_v2_service.api' 'projects/naxos-503510/locations/asia-northeast1/services/naxos-api'
terraform import 'google_cloud_run_v2_service.egress' 'projects/naxos-503510/locations/asia-northeast1/services/naxos-egress'
terraform import 'google_cloud_run_v2_service.internal' 'projects/naxos-503510/locations/asia-northeast1/services/naxos-internal'
terraform import 'google_cloud_run_v2_service_iam_member.egress_env_invoker["default"]' 'projects/naxos-503510/locations/asia-northeast1/services/naxos-egress/roles/run.invoker/serviceAccount:naxos2-env-default@naxos-503510.iam.gserviceaccount.com'
terraform import 'google_cloud_run_v2_service_iam_member.internal_egress_invoker' 'projects/naxos-503510/locations/asia-northeast1/services/naxos-internal/roles/run.invoker/serviceAccount:naxos2-egress@naxos-503510.iam.gserviceaccount.com'
terraform import 'google_cloud_run_v2_service_iam_member.internal_env_invoker["default"]' 'projects/naxos-503510/locations/asia-northeast1/services/naxos-internal/roles/run.invoker/serviceAccount:naxos2-env-default@naxos-503510.iam.gserviceaccount.com'
terraform import 'google_cloud_run_v2_service_iam_member.internal_scheduler_invoker' 'projects/naxos-503510/locations/asia-northeast1/services/naxos-internal/roles/run.invoker/serviceAccount:naxos2-scheduler@naxos-503510.iam.gserviceaccount.com'
terraform import 'google_cloud_scheduler_job.reconcile' 'projects/naxos-503510/locations/asia-northeast1/jobs/naxos-reconcile'
terraform import 'google_iam_workload_identity_pool.github[0]' 'projects/naxos-503510/locations/global/workloadIdentityPools/naxos-github'
terraform import 'google_iam_workload_identity_pool_provider.github[0]' 'projects/naxos-503510/locations/global/workloadIdentityPools/naxos-github/providers/github'
terraform import 'google_project_iam_member.api["roles/bigquery.dataEditor"]' 'naxos-503510/roles/bigquery.dataEditor/serviceAccount:naxos2-api@naxos-503510.iam.gserviceaccount.com'
terraform import 'google_project_iam_member.api["roles/bigquery.jobUser"]' 'naxos-503510/roles/bigquery.jobUser/serviceAccount:naxos2-api@naxos-503510.iam.gserviceaccount.com'
terraform import 'google_project_iam_member.api["roles/cloudscheduler.admin"]' 'naxos-503510/roles/cloudscheduler.admin/serviceAccount:naxos2-api@naxos-503510.iam.gserviceaccount.com'
terraform import 'google_project_iam_member.api["roles/cloudsql.client"]' 'naxos-503510/roles/cloudsql.client/serviceAccount:naxos2-api@naxos-503510.iam.gserviceaccount.com'
terraform import 'google_project_iam_member.api["roles/run.developer"]' 'naxos-503510/roles/run.developer/serviceAccount:naxos2-api@naxos-503510.iam.gserviceaccount.com'
terraform import 'google_project_iam_member.api_secret_admin' 'naxos-503510/roles/secretmanager.admin/serviceAccount:naxos2-api@naxos-503510.iam.gserviceaccount.com'
terraform import 'google_project_iam_member.deployer["roles/artifactregistry.writer"]' 'naxos-503510/roles/artifactregistry.writer/serviceAccount:naxos2-deployer@naxos-503510.iam.gserviceaccount.com'
terraform import 'google_project_iam_member.deployer["roles/cloudbuild.builds.editor"]' 'naxos-503510/roles/cloudbuild.builds.editor/serviceAccount:naxos2-deployer@naxos-503510.iam.gserviceaccount.com'
terraform import 'google_project_iam_member.deployer["roles/iam.serviceAccountUser"]' 'naxos-503510/roles/iam.serviceAccountUser/serviceAccount:naxos2-deployer@naxos-503510.iam.gserviceaccount.com'
terraform import 'google_project_iam_member.deployer["roles/logging.viewer"]' 'naxos-503510/roles/logging.viewer/serviceAccount:naxos2-deployer@naxos-503510.iam.gserviceaccount.com'
terraform import 'google_project_iam_member.deployer["roles/run.developer"]' 'naxos-503510/roles/run.developer/serviceAccount:naxos2-deployer@naxos-503510.iam.gserviceaccount.com'
terraform import 'google_project_iam_member.deployer["roles/serviceusage.serviceUsageConsumer"]' 'naxos-503510/roles/serviceusage.serviceUsageConsumer/serviceAccount:naxos2-deployer@naxos-503510.iam.gserviceaccount.com'
terraform import 'google_project_iam_member.environment_vertex["default"]' 'naxos-503510/roles/aiplatform.user/serviceAccount:naxos2-env-default@naxos-503510.iam.gserviceaccount.com'
terraform import 'google_project_service.enabled["aiplatform.googleapis.com"]' 'naxos-503510/aiplatform.googleapis.com'
terraform import 'google_project_service.enabled["artifactregistry.googleapis.com"]' 'naxos-503510/artifactregistry.googleapis.com'
terraform import 'google_project_service.enabled["bigquery.googleapis.com"]' 'naxos-503510/bigquery.googleapis.com'
terraform import 'google_project_service.enabled["cloudbuild.googleapis.com"]' 'naxos-503510/cloudbuild.googleapis.com'
terraform import 'google_project_service.enabled["cloudscheduler.googleapis.com"]' 'naxos-503510/cloudscheduler.googleapis.com'
terraform import 'google_project_service.enabled["iamcredentials.googleapis.com"]' 'naxos-503510/iamcredentials.googleapis.com'
terraform import 'google_project_service.enabled["run.googleapis.com"]' 'naxos-503510/run.googleapis.com'
terraform import 'google_project_service.enabled["secretmanager.googleapis.com"]' 'naxos-503510/secretmanager.googleapis.com'
terraform import 'google_project_service.enabled["sqladmin.googleapis.com"]' 'naxos-503510/sqladmin.googleapis.com'
terraform import 'google_secret_manager_secret.anthropic_api_key' 'projects/naxos-503510/secrets/anthropic-api-key'
terraform import 'google_secret_manager_secret.database_url' 'projects/naxos-503510/secrets/database-url'
terraform import 'google_secret_manager_secret_iam_member.anthropic_key_env["default"]' 'projects/naxos-503510/secrets/anthropic-api-key/roles/secretmanager.secretAccessor/serviceAccount:naxos2-env-default@naxos-503510.iam.gserviceaccount.com'
terraform import 'google_secret_manager_secret_iam_member.database_url_api' 'projects/naxos-503510/secrets/database-url/roles/secretmanager.secretAccessor/serviceAccount:naxos2-api@naxos-503510.iam.gserviceaccount.com'
terraform import 'google_secret_manager_secret_version.database_url' 'projects/1008450555904/secrets/database-url/versions/1'
terraform import 'google_service_account.api' 'projects/naxos-503510/serviceAccounts/naxos2-api@naxos-503510.iam.gserviceaccount.com'
terraform import 'google_service_account.deployer[0]' 'projects/naxos-503510/serviceAccounts/naxos2-deployer@naxos-503510.iam.gserviceaccount.com'
terraform import 'google_service_account.egress' 'projects/naxos-503510/serviceAccounts/naxos2-egress@naxos-503510.iam.gserviceaccount.com'
terraform import 'google_service_account.environment["default"]' 'projects/naxos-503510/serviceAccounts/naxos2-env-default@naxos-503510.iam.gserviceaccount.com'
terraform import 'google_service_account.scheduler' 'projects/naxos-503510/serviceAccounts/naxos2-scheduler@naxos-503510.iam.gserviceaccount.com'
terraform import 'google_service_account_iam_member.api_actas_environment["default"]' 'projects/naxos-503510/serviceAccounts/naxos2-env-default@naxos-503510.iam.gserviceaccount.com/roles/iam.serviceAccountUser/serviceAccount:naxos2-api@naxos-503510.iam.gserviceaccount.com'
terraform import 'google_service_account_iam_member.api_actas_scheduler' 'projects/naxos-503510/serviceAccounts/naxos2-scheduler@naxos-503510.iam.gserviceaccount.com/roles/iam.serviceAccountUser/serviceAccount:naxos2-api@naxos-503510.iam.gserviceaccount.com'
terraform import 'google_service_account_iam_member.deployer_wif[0]' 'projects/naxos-503510/serviceAccounts/naxos2-deployer@naxos-503510.iam.gserviceaccount.com/roles/iam.workloadIdentityUser/principalSet://iam.googleapis.com/projects/1008450555904/locations/global/workloadIdentityPools/naxos-github/attribute.repository/yoichiojima-2/naxos'
terraform import 'google_sql_database.naxos' 'projects/naxos-503510/instances/naxos-state/databases/naxos'
terraform import 'google_sql_database_instance.state' 'naxos-state'
terraform import 'google_sql_user.api' 'naxos//naxos-state'
terraform import 'google_storage_bucket.sessions["default"]' 'naxos-503510-sess-default'
terraform import 'google_storage_bucket_iam_member.deployer_build_staging[0]' 'b/naxos-503510_cloudbuild/roles/storage.admin/serviceAccount:naxos2-deployer@naxos-503510.iam.gserviceaccount.com'
terraform import 'google_storage_bucket_iam_member.sessions_api["default"]' 'b/naxos-503510-sess-default/roles/storage.objectViewer/serviceAccount:naxos2-api@naxos-503510.iam.gserviceaccount.com'
terraform import 'google_storage_bucket_iam_member.sessions_env["default"]' 'b/naxos-503510-sess-default/roles/storage.objectAdmin/serviceAccount:naxos2-env-default@naxos-503510.iam.gserviceaccount.com'
terraform import 'random_password.db' 'none'
